[package]
name = "life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = "0.12.0"
rand = "0.3.14"
image = "0.24.0"
minifb = "0.25.0"